emp_sale_manage/mysite2/urls.py
from django.contrib import admin
from app01.views import depart,user,admin,login,task,order,chart,upload,personal
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # 部门管理
    path('depart/list/',depart.depart_list),
    path('depart/add/',depart.depart_add),
    path('depart/delete/',depart.depart_delete),
    path('depart/<int:nid>/edit/',depart.depart_edit),
    path('depart/multi/',depart.depart_multi),

    # 用户管理
    path('user/list/',user.user_list),
    path('user/modelform/add/',user.user_modelform_add),
    path('user/<int:nid>/edit/',user.user_edit),
    path('user/<int:nid>/delete/',user.user_delete),

    # 组长管理
    path('admin/list/',admin.admin_list),
    path('admin/modelform/add/',admin.admin_modelform_add),
    path('admin/<int:nid>/edit/',admin.admin_edit),
    path('admin/<int:nid>/delete/',admin.admin_delete),
    path('admin/<int:nid>/reset/',admin.admin_reset),

    # 登录页面管理
    path('login/',login.login),
    path('logout/',login.logout),
    path('image/code/',login.code),

    # 任务页面管理：ajax求请
    path('task/list/',task.task_list),
    path('task/ajax/',task.task_ajax),  # 朝这个地址发的请求
    path('task/add/',task.task_add),  # 朝这个地址发的请求
    path('task/<int:nid>/delete/',task.task_delete),

    # 订单管理
    path('order/list/',order.order_list),  
    path('order/add/',order.order_add),
    path('order/delete/',order.order_delete),
    path('order/edit/',order.order_edit),
    path('order/editsave/',order.order_editsave),

    # 销售数据分析
    path('chart/list/',chart.chart_list),

    # 文件/图片上传
    path('upload/list/',upload.upload_list),
    path('upload/add/',upload.upload_add),
    path('upload/<int:nid>/delete/',upload.upload_delete),
    path('upload/<int:nid>/edit/',upload.upload_edit),

    # 个人页面
    path('personal/',personal.personal_list),
    path('introduce/',personal.introduce_list),

    # 路由重定向
    path('', depart.depart_list),
]

emp_sale_manage/app01/models.py
from django.db import models
from datetime import datetime
# Create your models here.


# 部门表
class Department(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title   # 输出department对象时返回的是title

# 员工表
class employee(models.Model):
    name = models.CharField(max_length=20,verbose_name='姓名')
    age = models.IntegerField(verbose_name="年龄")
    create_time = models.DateTimeField(verbose_name="入职日期")
    depart = models.ForeignKey(to='Department',to_field='id',on_delete=models.CASCADE,verbose_name="部门号") # 级联删除
    gender_choice = {
        (1,"男"),
        (2,"女"),
    }
    gender = models.SmallIntegerField(verbose_name="性别",choices=gender_choice)

    def __str__(self):
        return self.name   # 输出department对象时返回的是title


# 靓号管理
class PrettyNum(models.Model):
    """ 靓号表 """
    mobile = models.CharField(verbose_name="手机号",max_length=11)
    price = models.IntegerField(verbose_name="价格",default=0)

    level_choice = (
        (1,"1级"),
        (2,"2级"),
        (3,"3级"),
        (4,"4级")
    )
    level = models.SmallIntegerField(verbose_name="级别",choices=level_choice,default=1)

    status_choice = (
        (1,"已占用"),
        (2,"未占用")
    )
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choice,default=2)


# 管理员表
class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="用户名",max_length=32)
    password = models.CharField(verbose_name="密码",max_length=60)

    def __str__(self) -> str:
        return self.username
    

# 任务表
class Task(models.Model):
    """ 任务 """
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息")
    # emp_id
    emp = models.ForeignKey(verbose_name="员工", to="employee", on_delete=models.CASCADE,default=1)
    admin = models.ForeignKey(verbose_name="管理员", to="Admin", on_delete=models.CASCADE,default=1)


# 订单表
class Order(models.Model):
    """ 订单 """
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="商品", max_length=32)
    price = models.IntegerField(verbose_name="价格")
    create_time = models.DateTimeField(verbose_name="支付日期",default=datetime.now)
    category = models.CharField(verbose_name="商品分类", max_length=64,default=None)
    status_choices = (
        (1, "待支付"),
        (2, "已支付"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    # admin_id
    emp = models.ForeignKey(verbose_name="员工", to="employee", on_delete=models.CASCADE,default=1)


# 信息上传
class Boss(models.Model):
    """ 文件信息的上传 """
    name = models.CharField(verbose_name="姓名",max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.FileField(verbose_name="头像",max_length=64)

emp_sale_manage/app01/views/admin.py
from django.shortcuts import render,HttpResponse,redirect
from django.utils.safestring import mark_safe  # 标记安全字符串
from app01.utills.pagination import Pagination
from app01.utills.form import AdminModelForm,AdminResetModelForm
from app01 import models

# Create your views here.

# 管理员管理
def admin_list(request):
    """ 管理员列表 """
    queryset = models.Admin.objects.all()

    # ---------分页功能实现-----------
    page_object = Pagination(request,queryset,page_size=2)

    context = {
        'queryset':page_object.queryset,
        'page_string':page_object.html_data()
    }


    return render(request,'admin_list.html',context)


def admin_modelform_add(request):
    """添加管理员(modelform版)"""
    if request.method == 'GET':
        form = AdminModelForm()
        return render(request,"admin_modelform_add.html",{"form":form})
        
    else:
        form = AdminModelForm(data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('http://localhost:8000/admin/list/')
        else:
            return render(request,"admin_modelform_add.html",{"form":form})

def admin_delete(request,nid):
    """ 删除管理员 """
    if request.method == 'GET':
        models.Admin.objects.filter(id=nid).delete()

        # 重定向
        return redirect('http://127.0.0.1:8000/admin/list/')

def admin_edit(request,nid):
    """ 编辑管理员 """
    if request.method == 'GET':
        row_object = models.Admin.objects.filter(id=nid).first()
        return render(request,"admin_edit.html",{'row_object':row_object})

    else:
        new_username = request.POST.get("username")
        new_password = request.POST.get("password")
        models.Admin.objects.filter(id=nid).update(username=new_username,password=new_password)
        
        # page = math.ceil(nid/2)
        # 重定向
        return redirect('http://127.0.0.1:8000/admin/list/')

def admin_reset(request,nid):
    """ 重置密码(modelform版) """
    row_object = models.Admin.objects.filter(id=nid).first()

    if request.method == 'GET':
        form = AdminResetModelForm()  # instance字段可以指定input中,进去的value值 
        return render(request,"admin_modelform_reset.html",{"form":form,"nid":nid})
        
    else:
        form = AdminResetModelForm(data=request.POST,instance=row_object) # 此处添加一个instance就可以覆盖以前的密码

        if form.is_valid():
            form.save()
            return redirect('http://localhost:8000/admin/list/')
        else:
            return render(request,"admin_modelform_reset.html",{"form":form,"nid":nid})

emp_sale_manage/app01/views/chart.py
from django.shortcuts import render


def chart_list(request):
    return render(request=request,template_name="chart_list.html")

emp_sale_manage/app01/views/depart.py
from django.shortcuts import render,HttpResponse,redirect
from django.utils.safestring import mark_safe  # 标记安全字符串
from app01.utills.pagination import Pagination
from openpyxl import load_workbook
from app01 import models
# Create your views here.

# 部门管理
def depart_list(request):
    """ 部门列表 """
    queryset = models.Department.objects.all()

    context = {
        'queryset':queryset,
    }

    return render(request,'depart_list.html',context)


def depart_add(request):
    """ 添加部门 """
    if request.method == 'GET':
        return render(request,"depart_add.html")
    
    else:
        title = request.POST.get("title")
        models.Department.objects.create(title=title)

        # 重定向
        return redirect('http://127.0.0.1:8000/depart/list/')

def depart_delete(request):
    """ 删除部门 """
    nid = request.GET.get("nid")
    models.Department.objects.filter(id=nid).delete()
    return redirect('http://127.0.0.1:8000/depart/list/')

def depart_edit(request,nid):
    """ 编辑部门 """
    if request.method == 'GET':
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request,"depart_edit.html",{'row_object':row_object})

    else:
        new_title = request.POST.get("title")
        models.Department.objects.filter(id=nid).update(title=new_title)
        
        # 重定向
        return redirect('http://127.0.0.1:8000/depart/list/')

def depart_multi(request):
    """ 数据上传 """
    # 获取到文件对象
    file_object = request.FILES.get('exc')

    # 将对象传递给openpyxl
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

    # 读取excel表中的数据
    for row in sheet.iter_rows(min_row=2):
        for col in row:
            text = col.value
            exist = models.Department.objects.filter(title=text).exists()
            if not exist:
                models.Department.objects.create(title=text)
   
    return redirect('http://127.0.0.1:8000/depart/list/')

emp_sale_manage/app01/views/login.py
from django.shortcuts import render,HttpResponse,redirect
from app01 import models
from app01.utills.form import LoginForm
from app01.utills.code import check_code
from io import BytesIO



def login(request):
    """登录"""
    if request.method == 'GET':
        form = LoginForm()

        return render(request,"login.html",{"form":form})
    
    else:
        form = LoginForm(data=request.POST)
        if form.is_valid(): # 数据输入有效时
            # 1、拿到用户输入的数据
            # print(form.cleaned_data)  # 能拿到用户输入的用户名和密码和验证码  {'username': 'root', 'password': '1111', 'code':'xxx'}
            user_input_code = form.cleaned_data.pop('code')  # 因为数据库中没有code这个字段，所以需要干掉它,pop删除这个字段，并获取到对应的值

            # 2、验证码的校验
            code = request.session.get('image_code',"")  # 从session中取值
            if code.upper() != user_input_code.upper():  # 转大写
                form.add_error("code","验证码错误")
                return render(request, 'login.html', {"form":form})

            # 3、用户名和密码的校验
            admin_object = models.Admin.objects.filter(**form.cleaned_data).first()   
            if admin_object:  # 用户名和密码正确
                # 网站生成随机字符串; 写到用户浏览器的cookie中；在写入到session中；
                request.session["info"] = {'id': admin_object.id, 'username': admin_object.username}
                # 设置session可以保存7天
                request.session.set_expiry(60 * 60 * 24 * 7)
                return redirect('http://127.0.0.1:8000/admin/list/')
            else:
                form.add_error("password","用户名或密码错误")
                return render(request,'login.html',{"form":form})

        else:
            return render(request,"login.html",{"form":form})
        

def logout(request):
    """ 注销 """
    request.session.clear()

    return redirect('http://127.0.0.1:8000/login/')  # 回到登录页面


def code(request):
    """ 图片验证码 """
    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给Session设置60s超时，超时后image_code为空
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')   # 图片以二进制的形式存储在内存中
    # print(code_string)
    return HttpResponse(stream.getvalue())

        
        

emp_sale_manage/app01/views/order.py
from django.shortcuts import render,HttpResponse,redirect
from django.views.decorators.csrf import csrf_exempt  # post表单验证
from django.http import JsonResponse                  # 序列化
from app01.utills.form import OrderModelForm
from app01.models import Order
from app01.utills.pagination import Pagination 
from datetime import datetime
import random


def order_list(request):
    """ 点击弹窗展示 """
    # 数据
    queryset = Order.objects.all()
    # 分页
    page_object = Pagination(request,page_size=8,queryset=queryset)

    form = OrderModelForm()
    context = {
        "form":form,
        "queryset":page_object.queryset,
        "page_string":page_object.html_data()
    }
    

    return render(request=request,template_name='order_list.html',context=context)

@csrf_exempt
def order_add(request):
    """ 添加订单到数据库 """
    form = OrderModelForm(data=request.POST)
    if form.is_valid():
        # oid 字段自动生成
        form.instance.oid = datetime.now().strftime('%Y%m%d%H%M%S') + str(random.randint(1000,9999))
        form.save()
        return JsonResponse({"status":True})
    else:
        return JsonResponse({"status":False,"error":form.errors})

def order_delete(request):
    """删除订单"""
    # req = request # <WSGIRequest: GET '/order/delete/?uid=1'>
    # get = request.GET  # <QueryDict: {'uid': ['1']}>  querydict字典对象

    # 获取到字段对应的id
    uid = request.GET.get('uid')
    exists = Order.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({
            "status":False,
            "error":"删除失败，数据不存在。"
        })
    else:
        Order.objects.filter(id=uid).delete()  # 删除对应的字段
        return JsonResponse({'status':True})

def order_edit(request):
    uid = request.GET.get('uid')
    exists = Order.objects.filter(id=uid).exists()
    if exists:
        dict_data = Order.objects.filter(id=uid).values('title','price','status','emp','category').first()
        data = {
            'status':True,
            'data':dict_data
        }
        return JsonResponse(data)

    else:
        data = {
            'status':False,
            'error':"数据不存在"
        }
        return JsonResponse(data)

@csrf_exempt
def order_editsave(request):
    """ 将编辑的数据提交到数据库 """
    uid = request.GET.get('uid')
    form = OrderModelForm(data=request.POST)
    
    dict_data=request.POST.dict()  # 转为字典形式
    if form.is_valid():
        Order.objects.filter(id=uid).update(**dict_data)  # 更新字段
        data = {
            'status':True,
        }
        return JsonResponse(data)

    else:
        data = {
            'status':False,
            'error':form.errors
        }
        return JsonResponse(data)



    

emp_sale_manage/app01/views/personal.py
from django.shortcuts import render,HttpResponse


def personal_list(request):

    return render(request,"person.html")


def introduce_list(request):
    return render(request,"introduce.html")

emp_sale_manage/app01/views/task.py
from django.shortcuts import render,HttpResponse,redirect
from django.views.decorators.csrf import csrf_exempt  # 用于解决post请求需要csrf_token验证问题
from app01.utills.form import TaskModelForm
from app01.utills.pagination import Pagination  # 分页
from app01.models import Task
from django.http import JsonResponse  # 序列化存储
import json

def task_list(request):
    """ 任务列表 """
    # 拿数据
    queryset = Task.objects.all()
    # 分页
    page_object = Pagination(request,page_size=5,queryset=queryset)
    form = TaskModelForm()

    context = {
        "form":form,
        "queryset":page_object.queryset,
        "page_string":page_object.html_data()
    }

    return render(request,"task_list.html",context)


@csrf_exempt
def task_ajax(request):
    """ 请求处理 """
    print(request.GET)
    print(request.POST)

    data_dict = {
        "status":True,
        "data":{
            "name":"希区柯克",
            "flim":"惊魂记"
        }
    }
    return HttpResponse(json.dumps(data_dict))


@csrf_exempt
def task_add(request):
    """ 请求处理 """
    form = TaskModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        data_dict = {
            "status":True,
            "data":{
                "name":"诺兰",
                "flim":"星际穿越"
            }
        }
        return HttpResponse(json.dumps(data_dict))  # 将请求成功的数据返回给客户端
    
    else:
        data_dict = {
            "status":False,
            "error":form.errors
        }
        return HttpResponse(json.dumps(data_dict))  # 将请求失败的数据返回给客户端
    

def task_delete(request,nid):
    """ 删除任务 """
    if request.method == 'GET':
        Task.objects.filter(id=nid).delete()

        # 重定向
        return redirect('http://127.0.0.1:8000/task/list/')
    

emp_sale_manage/app01/templates/order_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <!-- Button-->
    <button type="button" class="btn btn-primary" id="buttonadd">
        点我弹框添加数据
    </button>

    <!-- Modal 弹框(添加) -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加数据</h4>
                </div>
                <div class="modal-body">
                    <!-- form表单 -->
                    <form id="formAdd">
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative;margin-bottom: 20px;">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg" style="color: red;position: absolute;"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary" id="buttonsave">保存</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal 弹框(删除) -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确定删除？</h4>
                <p style="margin: 10px 0;"> 删除后，所有关联的相关数据都会被删除。</p>
                <p style="text-align: right;">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>
        </div>
    </div>

    <!-- Modal 弹框(编辑) -->
    <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">编辑数据</h4>
                </div>
                <div class="modal-body">
                    <!-- form表单 -->
                    <form id="formEdit">
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative;margin-bottom: 20px;">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg" style="color: red;position: absolute;"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary" id="buttonedit">保存</button>
                </div>
            </div>
        </div>
    </div>

    <!-- 数据库中的数据展示 -->
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            订单列表
        </div>
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>订单号</th>
                <th>商品</th>
                <th>分类</th>
                <th>价格</th>
                <th>支付日期</th>
                <th>状态</th>
                <th>处理员工</th>
                <th>操作</th></th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <th>{{ obj.id }}</th>
                    <th>{{ obj.oid }}</th>
                    <td>{{ obj.title }}</td>
                    <td>{{ obj.category }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.create_time }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>{{ obj.emp.name }}</td>
                    <td>
                        <button uid="{{ obj.id }}" type="button" class="btn btn-danger btn-sm buttondelete">删除</button>
                        <button uid="{{ obj.id }}" type="button" class="btn btn-primary btn-sm buttonedit">编辑</button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- 分页 -->
    <nav aria-label="Page navigation">
        <form method="get">
            <ul class="pagination" style="margin: 50px 350px;">
                {{ page_string }}
                <li>
                    <input type="text" placeholder="..." name="page" class="form-control" style="width: 50px; float: left; margin-left: 10px;">
                    <button class="btn btn-default" type="submit">跳转</button>
                </li>
            </ul>
        </form>
    </nav>
</div>

{% endblock %}

{% block js %}

<script type="text/javascript">
    // 配置全局变量
    var DELETE_UID  
    var EDIT_UID

    $(function(){
        buttonAdd()
        buttonSaveDate()
        buttonDelete()
        buttonDeleteDate()
        buttonedit()
        buttoneditDate()
    })

    // 点击显示添加数据的弹框
    function buttonAdd(){
        $('#buttonadd').click(function(){
            $('#myModal').modal('show')
            // 清空表单
            // $(':input').val('')
        })
    }

    // 点击确认保存数据
    function buttonSaveDate(){
        $('#buttonsave').click(function(){
            $('.error-msg').empty()   // 清空错误信息
            $.ajax({
                url:"/order/add/",
                type:"post",
                data:$("#formAdd").serialize(),
                dataType:"JSON",
                success:function(res){
                    if(res.status) {
                        alert('小可爱，恭喜你添加成功！')
                        // $(':input').val('')    // 清空表单中所有的数据
                        // $("#formAdd")[0].reset();   // 清空表单  $("#formAdd")是jQuery对象 -> $("#formAdd")[0] DOM对象
                        $('#myModal').modal('hide')  // 添加完成自动隐藏
                        location.reload();  // 用JS实现页面的刷新
                    }
                    else{
                        $.each(res.error,function(key,value){  // 循环输出错误信息
                            // console.log(k,v[0])  title 这个字段是必填项
                            $('#id_' + key).next().text(value[0]);
                        })
                    }
                }
            })
        })
    }
    
    // 点击显示删除数据的弹框
    function buttonDelete(){
        $('.buttondelete').click(function(){
            $('#deleteModal').modal('show')

            DELETE_UID=$(this).attr('uid')   // this指的是.buttondelete对应的那个按钮
            // console.log(DELETE_UID)
        })
    }

    // 点击确认删除数据
    function buttonDeleteDate(){
        $('#btnConfirmDelete').click(function(){
            $.ajax({
                url:"/order/delete/",   // 请求会自动携带参数：/order/delete/?uid='xx'
                type:'get',
                dataType:"JSON",
                data:{
                    uid:DELETE_UID
                },
                success:function(res) {
                    if(res.status){
                        alert('恭喜你，删除字段成功了'),
                        $('#deleteModal').modal('hide'),
                        location.reload()
                    }
                    else(
                        alert(res.error),
                        $('#deleteModal').modal('hide')
                    )
                }
            })
        })
    }
   
    // 点击显示编辑数据的弹框（并带上原来的数据）
    function buttonedit(){
        $('.buttonedit').click(function(){
            // 获取id
            EDIT_UID = $(this).attr('uid')

            $.ajax({
                url:"/order/edit/",
                type:"get",
                data:{
                    uid:EDIT_UID
                },
                dataType:'JSON',
                success:function(res){
                    if(res.status) {
                        // 请求成功，展示弹框
                        $('#editModal').modal('show')
                        $.each(res.data,function(key,value){
                            $('#formEdit #id_' + key).val(value)   // 多级定位
                        })
                    }
                    else(
                        alert(res.error)
                    )
                }
            })
        })
    }

    // 点击确认保存编辑的数据
    function buttoneditDate(){
        $('#buttonedit').click(function(){
            $('#formEdit .error-msg').empty()   // 清空错误信息
            $.ajax({
                url:"/order/editsave/?uid=" + `${EDIT_UID}`,
                type:"post",
                data:$('#formEdit').serialize(),  // 获取表格中的数据
                dataType:'JSON',
                success:function(res){
                    if(res.status) {
                        $('#editModal').modal('hide')
                        location.reload()
                    }
                    else{
                        $.each(res.error,(key,value)=>{
                            $('#formEdit #id_' + key).next().text(value[0])
                        })
                    }
                }
            })
        })
    }

</script>

{% endblock %}

emp_sale_manage/app01/templates/user_list.html
{% extends 'layout.html' %} {% block content %}
<div class="container">
    <div style="margin-bottom:10px;">
        <a href="http://127.0.0.1:8000/user/modelform/add/" class="btn btn-success">添加员工</a>
    </div>

    <!-- 表格 -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span> 员工列表
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>年龄</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>部门ID</th>
                    <th>操作</th>

                </tr>
            </thead>
            <tbody>
                <!-- 模板语法 循环遍历数据库 -->
                {% for obj in queryset %}

                <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                    <!-- 模板语法自动部加（） -->
                    <td>{{ obj.get_gender_display }}</td>
                    <td>{{ obj.depart.title }}</td>
                    <td>
                        <a href="http://127.0.0.1:8000/user/{{ obj.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                        <a href="http://127.0.0.1:8000/user/{{ obj.id }}/delete/" class='btn btn-danger btn-xs'>删除</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- 分页导航 -->
    <nav aria-label="Page navigation">
        <form method="get">
            <ul class="pagination" style="margin: 50px 350px;">
                {{ page_string }}
                <li>
                    <input type="text" placeholder="..." name="page" class="form-control" style="width: 50px; float: left; margin-left: 10px;">
                    <button class="btn btn-default" type="submit">跳转</button>
                </li>
            </ul>
        </form>
    </nav>
</div>
{% endblock %}